&PARAM_IO
!--IO_LOG_BASENAME--
 IO_LOG_ALLNODE = .false.,
/

&PARAM_FILE
!--FILE_AGGREGATE--
/

&PARAM_FILE_CARTESC
 FILE_CARTESC_datacheck_criteria = 1.0D-4,
/

&PARAM_TIME
!--TIME_STARTDATE--
 TIME_STARTMS               = 0.D0,
!--TIME_DURATION--
 TIME_DURATION_UNIT         = "SEC",
 TIME_DT                    = 20.0D0,
 TIME_DT_UNIT               = "SEC",
 TIME_DT_ATMOS_DYN          = 5.0D0,
 TIME_DT_ATMOS_DYN_UNIT     = "SEC",
 TIME_DT_ATMOS_PHY_MP       = 20.0D0,
 TIME_DT_ATMOS_PHY_MP_UNIT  = "SEC",
 TIME_DT_ATMOS_PHY_CP       = 20.0D0,
 TIME_DT_ATMOS_PHY_CP_UNIT  = "SEC",
 TIME_DT_ATMOS_PHY_RD       = 600.D0,
 TIME_DT_ATMOS_PHY_RD_UNIT  = "SEC",
 TIME_DT_ATMOS_PHY_SF       = 20.0D0,
 TIME_DT_ATMOS_PHY_SF_UNIT  = "SEC",
 TIME_DT_ATMOS_PHY_BL       = 20.0D0,
 TIME_DT_ATMOS_PHY_BL_UNIT  = "SEC",
 TIME_DT_OCEAN              = 600.D0,
 TIME_DT_OCEAN_UNIT         = "SEC",
 TIME_DT_LAND               = 600.D0,
 TIME_DT_LAND_UNIT          = "SEC",
 TIME_DT_URBAN              = 600.D0,
 TIME_DT_URBAN_UNIT         = "SEC",
!--TIME_DT_ATMOS_RESTART--
 TIME_DT_ATMOS_RESTART_UNIT = "SEC",
!--TIME_DT_OCEAN_RESTART--
 TIME_DT_OCEAN_RESTART_UNIT = "SEC",
!--TIME_DT_LAND_RESTART--
 TIME_DT_LAND_RESTART_UNIT  = "SEC",
!--TIME_DT_URBAN_RESTART--
 TIME_DT_URBAN_RESTART_UNIT = "SEC",
!--TIME_END_RESTART_OUT--
/

&PARAM_COMM_CARTESC_NEST
!--ONLINE_DOMAIN_NUM--
!--ONLINE_IAM_PARENT--
!--ONLINE_IAM_DAUGHTER--
 ONLINE_BOUNDARY_USE_QHYD = .true.,
 ONLINE_AGGRESSIVE_COMM   = .true.,
 ONLINE_SPECIFIED_MAXRQ   = 10000,
/

&PARAM_STATISTICS
 STATISTICS_checktotal     = .false.,
 STATISTICS_use_globalcomm = .false.,
/

&PARAM_RESTART
!--RESTART_OUTPUT--
!--RESTART_IN_BASENAME--
!--RESTART_IN_POSTFIX_TIMELABEL--
!--RESTART_OUT_BASENAME--
!--RESTART_OUT_ADDITIONAL_COPIES--
!--RESTART_OUT_ADDITIONAL_BASENAME--
/

&PARAM_TOPO
!--TOPO_IN_BASENAME--
/

&PARAM_LANDUSE
!--LANDUSE_IN_BASENAME--
/

&PARAM_LAND_PROPERTY
!--LAND_PROPERTY_IN_FILENAME--
/

&PARAM_DOMAIN_CATALOGUE
!--DOMAIN_CATALOGUE_FNAME--
!--DOMAIN_CATALOGUE_OUTPUT--
/

#################################################
#
# model configuration: process
#
#################################################

&PARAM_PRC_CARTESC
 PRC_NUM_X      = 16,
 PRC_NUM_Y      = 16,
 PRC_PERIODIC_X = .false.,
 PRC_PERIODIC_Y = .false.,
/

#################################################
#
# model configuration: region
#
#################################################

&PARAM_ATMOS_GRID_CARTESC_INDEX
 KMAX = 47,
 IMAX = 16,
 JMAX = 16,
/

&PARAM_LAND_GRID_CARTESC_INDEX
 LKMAX = 7,
/

&PARAM_URBAN_GRID_CARTESC_INDEX
 UKMAX = 5,
/

&PARAM_LAND_GRID_CARTESC
 LDZ = 0.05D0, 0.15D0, 0.30D0, 0.50D0, 1.0D0, 1.0D0, 1.0D0,
/

&PARAM_URBAN_GRID_CARTESC
 UDZ = 0.01D0, 0.01D0, 0.03D0, 0.05D0, 0.10D0,
/

&PARAM_OCEAN_GRID_CARTESC_INDEX
 OKMAX = 1,
/

&PARAM_ATMOS_GRID_CARTESC
 DX = 6000.D0,
 DY = 6000.D0,
 ! 04/02/2019
 FZ(:) =    160.0000D0,   320.0000D0,   480.0000D0,   640.0000D0,   800.0000D0,
            971.2000D0,  1154.3840D0,  1350.3910D0,  1560.1184D0,  1784.5267D0,
           2024.6437D0,  2281.5688D0,  2556.4788D0,  2850.6323D0,  3165.3767D0,
           3502.1533D0,  3862.5044D0,  4248.0801D0,  4660.6460D0,  5102.0913D0,
           5574.4380D0,  6079.8491D0,  6620.6392D0,  7199.2847D0,  7818.4355D0,
           8480.9268D0,  9189.7920D0,  9948.2773D0, 10759.8564D0, 11628.2461D0,
          12528.2461D0, 13428.2461D0, 14328.2461D0, 15228.2461D0, 16128.2461D0,
          17028.2461D0, 17928.2461D0, 18828.2461D0, 19728.2461D0, 20628.2461D0,
          21580.7617D0, 22588.8574D0, 23655.7754D0, 24784.9473D0, 25980.0059D0,
          27244.7969D0, 28583.3887D0,
 BUFFER_DZ = 5000.D0,
 BUFFER_DX = 120000.D0,
 BUFFER_DY = 120000.D0,
/

&PARAM_MAPPROJECTION
! Osaka PAWR
 MAPPROJECTION_basepoint_lon = 134.9512D0,
 MAPPROJECTION_basepoint_lat =  34.7105D0,
!
 MAPPROJECTION_type          = 'LC',
 MAPPROJECTION_LC_lat1       =  30.00D0,
 MAPPROJECTION_LC_lat2       =  40.00D0,
/

#################################################
#
# model configuration: administrator
#
#################################################

&PARAM_CONST
 CONST_THERMODYN_TYPE = "SIMPLE",
/

&PARAM_ATMOS
 ATMOS_DYN_TYPE    = "HEVI",
 ATMOS_PHY_MP_TYPE = "TOMITA08",
 ATMOS_PHY_CP_TYPE = "KF",
 ATMOS_PHY_RD_TYPE = "MSTRNX",
 ATMOS_PHY_SF_TYPE = "COUPLE",
 ATMOS_PHY_TB_TYPE = "SMAGORINSKY",
 ATMOS_PHY_BL_TYPE = "MYNN",
/

&PARAM_OCEAN
 OCEAN_DYN_TYPE = "INIT",
 OCEAN_SFC_TYPE = "FIXED-TEMP"
/

&PARAM_LAND
 LAND_DYN_TYPE = "BUCKET",
 LAND_SFC_TYPE = "SKIN",
/

! r0051
&PARAM_LAND_DYN_BUCKET
 LAND_DYN_BUCKET_UPDATE_BOTTOM_TEMP  = .false.,
 LAND_DYN_BUCKET_UPDATE_BOTTOM_WATER = .true.,
/

! r0051
&PARAM_BULKFLUX
 BULKFLUX_type = "B91W01",
/

&PARAM_URBAN
 URBAN_DYN_TYPE = "KUSAKA01",
/

#################################################
#
# model configuration: atmosphere
#
#################################################

&PARAM_ATMOS_VARS
 ATMOS_VARS_CHECKRANGE = .true.,
/

&PARAM_ATMOS_REFSTATE
 ATMOS_REFSTATE_TYPE = "INIT",
 ATMOS_REFSTATE_UPDATE_DT   = 10800.D0,
/

&PARAM_ATMOS_BOUNDARY
 ATMOS_BOUNDARY_TYPE        = "REAL",
!--ATMOS_BOUNDARY_IN_BASENAME--
!--ATMOS_BOUNDARY_START_DATE--
 ATMOS_BOUNDARY_USE_DENS    = .true.,
 ATMOS_BOUNDARY_USE_QHYD    = .false.,
!--ATMOS_BOUNDARY_UPDATE_DT--
! ATMOS_BOUNDARY_ALPHAFACT_DENS = 0.25D0,
! ATMOS_BOUNDARY_TAUX        = 20.0D0,
! ATMOS_BOUNDARY_TAUY        = 20.0D0,
 ATMOS_BOUNDARY_LINEAR_H    = .false.,
 ATMOS_BOUNDARY_EXP_H       = 2.d0,
/

&PARAM_ATMOS_DYN
 ATMOS_DYN_TINTEG_LARGE_TYPE          = "EULER",
 ATMOS_DYN_TINTEG_SHORT_TYPE          = "RK4",
 ATMOS_DYN_TINTEG_TRACER_TYPE         = "RK3WS2002",
 ATMOS_DYN_FVM_FLUX_TYPE              = "UD3",          ! r0051
 ATMOS_DYN_FVM_FLUX_TRACER_TYPE       = "UD3KOREN1993",
 ATMOS_DYN_FLAG_FCT_TRACER            = .false.,
 ATMOS_DYN_NUMERICAL_DIFF_COEF        = 1.D-4,
 ATMOS_DYN_NUMERICAL_DIFF_COEF_TRACER = 0.0D0,
 ATMOS_DYN_CORIOLIS_TYPE = "SPHERE",
 ATMOS_DYN_WDAMP_HEIGHT               = 15.D3,
/

&PARAM_ATMOS_PHY_TB_SMG
 ATMOS_PHY_TB_SMG_horizontal = .true.,
/

&PARAM_ATMOS_PHY_RD_MSTRN
 ATMOS_PHY_RD_MSTRN_TOA                   = 100.D0,
 ATMOS_PHY_RD_MSTRN_KADD                  = 30,
!--ATMOS_PHY_RD_MSTRN_GASPARA_IN_FILENAME--
!--ATMOS_PHY_RD_MSTRN_AEROPARA_IN_FILENAME--
!--ATMOS_PHY_RD_MSTRN_HYGROPARA_IN_FILENAME--
 ATMOS_PHY_RD_MSTRN_NBAND                 = 29,
/

&PARAM_ATMOS_PHY_RD_PROFILE
!--ATMOS_PHY_RD_PROFILE_CIRA86_IN_FILENAME--
!--ATMOS_PHY_RD_PROFILE_MIPAS2001_IN_BASENAME--
/

&PARAM_ATMOS_PHY_MP
 MP_ntmax_sedimentation = 6,
/

!&PARAM_ATMOS_PHY_MP_TOMITA08
! Default Tomita (2008) parameters are used
!/

#################################################
#
# model configuration: ocean
#
#################################################

&PARAM_OCEAN_VARS
 OCEAN_VARS_CHECKRANGE = .true.,
/

&PARAM_OCEAN_DYN_SLAB
 OCEAN_DYN_SLAB_DEPTH = 10.D0,
/

&PARAM_OCEAN_ROUGHNESS
 OCEAN_ROUGHNESS_TYPE = "MOON07",
/

#################################################
#
# model configuration: land
#
#################################################

&PARAM_LAND_VARS
 LAND_VARS_CHECKRANGE = .false.,
/

&PARAM_LAND_DYN_BUCKET
 LAND_DYN_BUCKET_UPDATE_BOTTOM_TEMP  = .false.,
 LAND_DYN_BUCKET_UPDATE_BOTTOM_WATER = .true.,
/

#################################################
#
# model configuration: urban
#
#################################################

&PARAM_URBAN_VARS
 URBAN_VARS_CHECKRANGE = .false.,
/

#################################################
#
# model configuration: coupler
#
#################################################

! Do not turn on sensible heat (STRGR, STRGG, & STRGG should be zero)
&PARAM_URBAN_DYN_KUSAKA01
 ZR         = 15.0D0,
 roof_width = 7.5D0,
 road_width = 22.5D0,
 AH         = 0.0D0,
 ALH        = 0.0D0,
! STRGR      = 0.24D0,
! STRGB      = 0.009D0,
! STRGG      = 0.24D0,
 STRGR      = 0.0D0,
 STRGB      = 0.0D0,
 STRGG      = 0.0D0,
 AKSR       = 2.28D0,
 AKSB       = 2.28D0,
 AKSG       = 2.28D0,
 ALBR       = 0.20D0,
 ALBB       = 0.20D0,
 ALBG       = 0.20D0,
 EPSR       = 0.97D0,
 EPSB       = 0.97D0,
 EPSG       = 0.97D0,
 Z0R        = 0.005D0,
 Z0B        = 0.005D0,
 Z0G        = 0.005D0,
 CAPR       = 2.01D6,
 CAPB       = 2.01D6,
 CAPG       = 2.01D6,
/

#################################################
#
# model configuration: history
#
#################################################

&PARAM_FILE_HISTORY
!--FILE_HISTORY_DEFAULT_BASENAME--
!--FILE_HISTORY_DEFAULT_TINTERVAL--
 FILE_HISTORY_DEFAULT_TUNIT     = "SEC",
 FILE_HISTORY_DEFAULT_TAVERAGE  = .false.,
 FILE_HISTORY_DEFAULT_DATATYPE  = "REAL4",
 FILE_HISTORY_DEFAULT_ZCOORD    = "model",
 FILE_HISTORY_OUTPUT_STEP0      = .true.,
!--FILE_HISTORY_DEFAULT_POSTFIX_TIMELABEL--
/

&PARAM_FILE_HISTORY_CARTESC
 FILE_HISTORY_CARTESC_BOUNDARY = .false.,
/

&HISTORY_ITEM name='DENS' / ! Nesting
&HISTORY_ITEM name='MOMZ' / ! Nesting
&HISTORY_ITEM name='MOMX' / ! Nesting
&HISTORY_ITEM name='MOMY' / ! Nesting
&HISTORY_ITEM name='RHOT' / ! Nesting

&HISTORY_ITEM name='QV'   / ! Nesting/LETKF
&HISTORY_ITEM name='QC'   / ! Nesting/LETKF
&HISTORY_ITEM name='QR'   / ! Nesting/LETKF
&HISTORY_ITEM name='QI'   / ! Nesting/LETKF
&HISTORY_ITEM name='QS'   / ! Nesting/LETKF
&HISTORY_ITEM name='QG'   / ! Nesting/LETKF
&HISTORY_ITEM name='QHYD' /

&HISTORY_ITEM name='T'    / ! LETKF
&HISTORY_ITEM name='PRES' / ! LETKF
&HISTORY_ITEM name='U'    / ! LETKF
&HISTORY_ITEM name='V'    / ! LETKF
&HISTORY_ITEM name='W'    / ! LETKF
&HISTORY_ITEM name='RH'   / ! LETKF (not analyzed)

&HISTORY_ITEM name='PREC', taverage=.true. /
&HISTORY_ITEM name='RAIN', taverage=.true. /
&HISTORY_ITEM name='SNOW', taverage=.true. /

&HISTORY_ITEM name='SFC_PRES'   / ! LETKF (not analyzed)
&HISTORY_ITEM name='SFC_TEMP'   / ! LETKF (not analyzed)

&HISTORY_ITEM name='U10' / ! LETKF (not analyzed)
&HISTORY_ITEM name='V10' / ! LETKF (not analyzed)
&HISTORY_ITEM name='T2'  / ! Nesting/LETKF (not analyzed)
&HISTORY_ITEM name='Q2'  / ! LETKF (not analyzed)
&HISTORY_ITEM name="MSLP" / ! Nesting


&HISTORY_ITEM name='CAPE' /


&HISTORY_ITEM name='OSR' /
&HISTORY_ITEM name='OLR' /
&HISTORY_ITEM name='SLR' /
&HISTORY_ITEM name='SSR' /


&HISTORY_ITEM name="OCEAN_TEMP"     / ! Nesting
&HISTORY_ITEM name="OCEAN_SFC_TEMP" / ! Nesting
&HISTORY_ITEM name="OCEAN_SFC_ALB_IR_dir"   / ! Nesting
&HISTORY_ITEM name="OCEAN_SFC_ALB_IR_dif"   / ! Nesting
&HISTORY_ITEM name="OCEAN_SFC_ALB_NIR_dir"   / ! Nesting
&HISTORY_ITEM name="OCEAN_SFC_ALB_NIR_dif"   / ! Nesting
&HISTORY_ITEM name="OCEAN_SFC_ALB_VIS_dir"   / ! Nesting
&HISTORY_ITEM name="OCEAN_SFC_ALB_VIS_dif"   / ! Nesting
&HISTORY_ITEM name="OCEAN_SFC_Z0M"  / ! Nesting


&HISTORY_ITEM name="LAND_TEMP"     / ! Nesting
&HISTORY_ITEM name="LAND_WATER"    / ! Nesting
&HISTORY_ITEM name="LAND_SFC_TEMP" / ! Nesting
&HISTORY_ITEM name="LAND_SFC_ALB_IR_dir"   / ! Nesting
&HISTORY_ITEM name="LAND_SFC_ALB_IR_dif"   / ! Nesting
&HISTORY_ITEM name="LAND_SFC_ALB_NIR_dir"   / ! Nesting
&HISTORY_ITEM name="LAND_SFC_ALB_NIR_dif"   / ! Nesting
&HISTORY_ITEM name="LAND_SFC_ALB_VIS_dir"   / ! Nesting
&HISTORY_ITEM name="LAND_SFC_ALB_VIS_dif"   / ! Nesting

&HISTORY_ITEM name="URBAN_SFC_TEMP" / ! Nesting

#################################################
#
# model configuration: monitor
#
#################################################

&PARAM_MONITOR
!--MONITOR_OUT_BASENAME--
 MONITOR_STEP_INTERVAL = 120,
/

&MONITOR_ITEM name="QDRY" /
&MONITOR_ITEM name="QTOT" /
&MONITOR_ITEM name="ENGT" /
&MONITOR_ITEM name="ENGP" /
&MONITOR_ITEM name="ENGK" /
&MONITOR_ITEM name="ENGI" /

&MONITOR_ITEM name="ENGFLXT" /

&MONITOR_ITEM name="ENGSFC_SH" /
&MONITOR_ITEM name="ENGSFC_LH" /
&MONITOR_ITEM name="ENGSFC_RD" /
&MONITOR_ITEM name="ENGTOA_RD" /

