#!/bin/bash                                                                    

# copied from /work/hp150019/share/nowcast/bin/jit-lwatch on 8/28/2019

USER=honda

TOP=/work/hp150019/share/${USER}/jitdt/online

DATA_DIR=/work/hp150019/share/nowcast/kobe/data/
#DAEMON=./lwatcher
DAEMON=/work/hp150019/share/nowcast/bin/lwatcher

LOGFILE=$TOP/LWATCHLOG
PID_FILE=$TOP/LWATCH_PID
CONF_FILE=$TOP/etc/conf
OPTIONS="-D -d -v -h 5 -c $CONF_FILE -f $LOGFILE"
OPTIONS2="-d -v -c $CONF_FILE -f $LOGFILE"

case "$1" in
  start)
        echo -n "Removing data: $DATA_DIR"
        rm -f $DATA_DIR/*
        echo "done"
        echo -n "Starting lwatcher: " $OPTIONS $DATA_DIR
        $DAEMON $OPTIONS $DATA_DIR >$PID_FILE
        echo "done"
        ;;
  start2)
        echo -n "Removing data: $DATA_DIR"
        rm -f $DATA_DIR/*
        echo "done"
        echo -n "Starting lwatcher: "
        $DAEMON $OPTIONS2 $DATA_DIR >$PID_FILE
        echo "done"
        ;;
  stop)
        echo -n "Stopping lwatcher: "
        kill -KILL `cat $PID_FILE`
        echo "done"
        ;;
  *)
        echo "Usage: $0 start" >&2
        echo "       $0 stop" >&2
        ;;
esac

exit 0
