#!/bin/bash                                                                    

# copied from /work/hp150019/share/nowcast/bin/jit-lwatch-offline on 7/31/2019

USER=$(id -nu)

TOP=/work/hp150019/share/${USER}/jitdt/offline
DATA_DIR=$TOP/data
DAEMON=/work/hp150019/share/nowcast/bin/lwatcher
LOGFILE=$TOP/LWATCHLOG
PID_FILE=$TOP/LWATCH_PID
#CONF_FILE=$TOP/etc/conf
CONF_FILE=/work/hp150019/share/nowcast/saitama/etc/conf
OPTIONS="-D -d -v -h 5 -c $CONF_FILE -f $LOGFILE"
OPTIONS2="-d -v -c $CONF_FILE -f $LOGFILE"

case "$1" in
  start)
        echo "Removing data: $DATA_DIR"
        rm -f $DATA_DIR/*
        echo "Starting lwatcher: " $OPTIONS $DATA_DIR
        $DAEMON $OPTIONS $DATA_DIR >$PID_FILE
        echo; echo "done"
        ;;
  start2)
        echo -n "Removing data: $DATA_DIR"
        rm -f $DATA_DIR/*
        echo "done"
        echo -n "Starting lwatcher: "
        $DAEMON $OPTIONS2 $DATA_DIR >$PID_FILE
        echo "done"
        ;;
  stop)
        echo -n "Stopping lwatcher: "
        kill -KILL `cat $PID_FILE`
        echo "done"
        ;;
  *)
        echo "Usage: $0 start" >&2
        echo "       $0 stop" >&2
        ;;
esac

exit 0
