&PARAM_IO
!--IO_LOG_BASENAME--
 IO_LOG_ALLNODE  = .false.,
/

&PARAM_FILE
!--FILE_AGGREGATE--
/

&PARAM_TIME
!--TIME_STARTDATE--
 TIME_STARTMS   = 0.D0,
/

&PARAM_STATISTICS
 STATISTICS_checktotal     = .true.,
 STATISTICS_use_globalcomm = .true.,
/

&PARAM_RESTART
!--RESTART_OUTPUT--
!--RESTART_OUT_BASENAME--
!--RESTART_OUT_POSTFIX_TIMELABEL--
/

&PARAM_TOPO
!--TOPO_IN_BASENAME--
/

&PARAM_LANDUSE
!--LANDUSE_IN_BASENAME--
/

&PARAM_LAND_PROPERTY
!--LAND_PROPERTY_IN_FILENAME--
/

&PARAM_MKINIT
 MKINIT_initname = "REAL",
/

&PARAM_MKINIT_REAL_ATMOS
!--BASENAME_BOUNDARY--
!--BASENAME_ORG--
!--FILETYPE_ORG--
!#--NUMBER_OF_FILES--
!#--NUMBER_OF_TSTEPS--
!#--NUMBER_OF_SKIP_TSTEPS--
!--BOUNDARY_UPDATE_DT--
! USE_FILE_DENSITY = .false.,
/

&PARAM_MKINIT_REAL_OCEAN
!#--BASENAME_ORG--
!#--FILETYPE_ORG--
!#--NUMBER_OF_FILES--
!#--NUMBER_OF_TSTEPS--
!#--NUMBER_OF_SKIP_TSTEPS--
! INTRP_OCEAN_SFC_TEMP = "mask",
! INTRP_OCEAN_TEMP = "mask",
/

&PARAM_MKINIT_REAL_LAND
!#--BASENAME_ORG--
!#--FILETYPE_ORG--
!#--NUMBER_OF_FILES--
!#--NUMBER_OF_TSTEPS--
!#--NUMBER_OF_SKIP_TSTEPS--
! USE_FILE_LANDWATER   = .true.,
! INTRP_LAND_TEMP      = "mask",
! INTRP_LAND_WATER     = "fill",
! INTRP_LAND_SFC_TEMP  = "fill",
/

&PARAM_COMM_CARTESC_NEST
!--OFFLINE_PARENT_BASENAME--
!--OFFLINE_PARENT_PRC_NUM_X--
!--OFFLINE_PARENT_PRC_NUM_Y--
!--LATLON_CATALOGUE_FNAME--
! NEST_INTERP_LEVEL = 12,
/

#################################################
#
# model configuration: process
#
#################################################

&PARAM_PRC_CARTESC
 PRC_NUM_X      = 16,
 PRC_NUM_Y      = 16,
 PRC_PERIODIC_X = .false.,
 PRC_PERIODIC_Y = .false.,
/

#################################################
#
# model configuration: region
#
#################################################

&PARAM_ATMOS_GRID_CARTESC_INDEX
 KMAX = 47,
 IMAX = 16,
 JMAX = 16,
/

&PARAM_LAND_GRID_CARTESC_INDEX
 LKMAX = 7,
/

&PARAM_LAND_GRID_CARTESC
 LDZ = 0.05D0, 0.15D0, 0.3D0, 0.5D0, 1.0D0, 1.0D0, 1.0D0,
/

&PARAM_URBAN_GRID_CARTESC_INDEX
 UKMAX = 5,
/

&PARAM_URBAN_GRID_CARTESC
 UDZ = 0.01D0, 0.01D0, 0.03D0, 0.05D0, 0.10D0,
/

&PARAM_OCEAN_GRID_CARTESC_INDEX
 OKMAX = 1,
/

&PARAM_ATMOS_GRID_CARTESC
 DX = 6000.D0,
 DY = 6000.D0,
 FZ(:) =    160.0000D0,   320.0000D0,   480.0000D0,   640.0000D0,   800.0000D0,
            971.2000D0,  1154.3840D0,  1350.3910D0,  1560.1184D0,  1784.5267D0,
           2024.6437D0,  2281.5688D0,  2556.4788D0,  2850.6323D0,  3165.3767D0,
           3502.1533D0,  3862.5044D0,  4248.0801D0,  4660.6460D0,  5102.0913D0,
           5574.4380D0,  6079.8491D0,  6620.6392D0,  7199.2847D0,  7818.4355D0,
           8480.9268D0,  9189.7920D0,  9948.2773D0, 10759.8564D0, 11628.2461D0,
          12528.2461D0, 13428.2461D0, 14328.2461D0, 15228.2461D0, 16128.2461D0,
          17028.2461D0, 17928.2461D0, 18828.2461D0, 19728.2461D0, 20628.2461D0,
          21580.7617D0, 22588.8574D0, 23655.7754D0, 24784.9473D0, 25980.0059D0,
          27244.7969D0, 28583.3887D0,
 BUFFER_DZ = 5000.D0,
 BUFFER_DX = 120000.D0,
 BUFFER_DY = 120000.D0,
/

&PARAM_MAPPROJECTION
 MAPPROJECTION_basepoint_lon = 134.9512D0,
 MAPPROJECTION_basepoint_lat =  34.7105D0,
 MAPPROJECTION_type          = 'MER',
! MAPPROJECTION_type          = 'LC',
! MAPPROJECTION_LC_lat1       =  30.00D0,
! MAPPROJECTION_LC_lat2       =  40.00D0,
/

#################################################
#
# model configuration: administrator
#
#################################################

&PARAM_ATMOS
 ATMOS_DYN_TYPE    = "HEVI",
 ATMOS_PHY_MP_TYPE = "TOMITA08",
 ATMOS_PHY_CP_TYPE = "KF",
 ATMOS_PHY_RD_TYPE = "MSTRNX",
 ATMOS_PHY_SF_TYPE = "COUPLE",
 ATMOS_PHY_TB_TYPE = "SMAGORINSKY",
 ATMOS_PHY_BL_TYPE = "MYNN",
/

&PARAM_OCEAN
 OCEAN_DYN_TYPE = "INIT",
 OCEAN_SFC_TYPE = "FIXED-TEMP",
/

&PARAM_LAND
 LAND_DYN_TYPE = "BUCKET",
 LAND_SFC_TYPE = "SKIN",
/

&PARAM_URBAN
 URBAN_DYN_TYPE = "KUSAKA01",
/
